name: 'Set repository permissions'
description: 'A action used to set user or team permissions for repositories'
author: 'Madis Koosaar'
branding:
  color: "yellow"
  icon: 'action'
  
inputs:
  token: 
    description:  "GitHub PAT token"
    required: true
  target-org : 
    description: "Target organization name where the repositories are located"
    required: true
  repositories :
    description: "JSON array of repositories to set permissions for"
    required: true
  teamsOrUsers :
    description: "JSON array of teams or users to set permissions for"
    required: true
  action-type:
    description: "Action type to perform. Can be 'USER' or 'TEAM'. Default is TEAM"
    required: true
    default: "TEAM"
  issue-nr:
    description: "Issue number to comment on"
    required: true
  target-repo :
    description: "Target repository name where the issue is located"
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
