# create workflow that will validate pull request compilation and run tests

# create workflow that will validate pull request compilation and run tests

name: Validate pull request

on: 
    pull_request:
        branches: [ main ]

jobs:
    ci-build:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            # setup node and cache node modules
            - uses: actions/setup-node@v4.1.0
              with:
                node-version: '20'
                cache: 'npm'
            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run all

            - name: Test
              run: npm run test
