# Create a workflow that will compile the typescript composite action and update the main branch with the compiled code

name: Compile and publish composite action

permissions:
    contents: write

on:
    push:
        branches:
        - main
        paths-ignore:
        - 'dist/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        
       # setup node and cache node modules
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
            cache: 'npm'
        - name: Install dependencies
          run: npm ci

        - name: Build
          run: npm run all
        
        - uses: actions/upload-artifact@v2
          with:
            name: dist
            path: dist

        - uses: actions/checkout@v3
          with:
            ref: main
            path: main
            token: ${{ secrets.REPO_TOKEN }}

        - uses: actions/download-artifact@v2
          with:
            name: dist
            path: main/dist

      # Commit and push the compiled code to the main branch dist folder
        
        - name: Commit and push compiled code
          run: |
            if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
              echo "Detected uncommitted changes after build.  See status below:"
              git diff            
              git config --global user.name "github-actions[bot]"
              git add . 
              git commit -m "update dist from build"
              git push 
            fi
          working-directory: main
          shell: bash

          

      
      
