# create a release workflow that will take in version number and create a release and tag it
name: Release


  

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true
        default: '0.0.0'
        
jobs:
    release:
        if: github.repository_owner == 'madkoo'
        name: Create Release
        runs-on: ubuntu-latest
        permissions:
          contents: write
          packages: write
        steps:
        
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Get first number from version
          id: first_number
          run: echo "version=$(echo ${{ github.event.inputs.version }} | cut -d. -f1)" >> $GITHUB_OUTPUT     

        # - name: Create Release
        #   id: create_release
        #   uses: actions/create-release@v1
        #   env:
        #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   with:
        #       tag_name: 'v${{ steps.first_number.outputs.version }}'
        #       release_name: Release v${{ github.event.inputs.version }}
        #       draft: false
        #       prerelease: false

        # create a release and tag it or replace tag if it already exists
        - uses: ncipollo/release-action@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: 'v${{ steps.first_number.outputs.version }}'
            name: Release v${{ github.event.inputs.version }}
            body: |
              Release v${{ github.event.inputs.version }}
            draft: false
            prerelease: false
            allowUpdates: true
      


        
